name = "gleam_pgo"
version = "0.3.0"
licences = ["Apache-2.0"]
description = "Gleam bindings to the PGO PostgreSQL client"

repository = { type = "github", user = "gleam-experiments", repo = "pgo" }
links = [
  { title = "Website", href = "https://gleam.run" },
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = "~> 0.19"
pgo = "~> 0.11"

[dev-dependencies]
gleeunit = "~> 0.6"
