name = "gleam_pgo"
version = "0.4.1"
licences = ["Apache-2.0"]
description = "Gleam bindings to the PGO PostgreSQL client"

gleam = ">= 0.30.0"

repository = { type = "github", user = "gleam-experiments", repo = "pgo" }
links = [
  { title = "Website", href = "https://gleam.run" },
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = "~> 0.20"
pgo = "~> 0.12"

[dev-dependencies]
gleeunit = "~> 0.6"
