name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: erlef/setup-beam@v1.13.0
        with:
          otp-version: "24.2"
          gleam-version: "nightly"
      - run: gleam build
      # TODO: enable testing again
      # - run: gleam test
      - run: gleam format --check src test
